import Carousel from '../components/Carousel';
import Nav from '../components/ui/Nav';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'muebles,tvs,aires,tecnologia,electrodomesticos',
}


export default function Home() {
  return (
    <main>
       <Nav/>
       <Carousel/>
      
    </main>
    
  
  )
}
